spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lonely?serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8mb4
    username: root
    password: root
custom:
  username: admin
  password: 1